/**
 * Tests for log-writer — one-liner format, file auto-creation, append behavior
 */

import { mkdtempSync, rmSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { formatLogLine, appendLog } from './log-writer.js';
import type { NotificationEvent } from '../types.js';

function makeEvent(overrides: Partial<NotificationEvent> = {}): NotificationEvent {
  return {
    id: 'test-id',
    timestamp: new Date('2026-03-17T14:30:00'),
    task: 'my-task',
    type: 'task_complete',
    level: 'info',
    message: 'Task completed successfully',
    ...overrides,
  };
}

describe('log-writer', () => {
  let flowDir: string;

  beforeEach(() => {
    flowDir = mkdtempSync(join(tmpdir(), 'log-writer-test-'));
  });

  afterEach(() => {
    rmSync(flowDir, { recursive: true, force: true });
  });

  describe('formatLogLine', () => {
    it('should format info level with checkmark icon', () => {
      const event = makeEvent({ level: 'info' });
      const line = formatLogLine(event);
      expect(line).toBe('[2026-03-17 14:30] \u2705 my-task: Task completed successfully');
    });

    it('should format warn level with pause icon', () => {
      const event = makeEvent({ level: 'warn', message: 'Something slow' });
      const line = formatLogLine(event);
      expect(line).toContain('\u23F8\uFE0F');
      expect(line).toContain('my-task: Something slow');
    });

    it('should format error level with cross icon', () => {
      const event = makeEvent({ level: 'error', message: 'Failed hard' });
      const line = formatLogLine(event);
      expect(line).toContain('\u274C');
      expect(line).toContain('my-task: Failed hard');
    });

    it('should handle Date object timestamps', () => {
      const event = makeEvent({ timestamp: new Date('2026-01-05T08:05:00') });
      const line = formatLogLine(event);
      expect(line).toMatch(/^\[2026-01-05 08:05\]/);
    });

    it('should handle string timestamps by converting to Date', () => {
      const event = makeEvent({ timestamp: '2026-06-15T22:00:00Z' as unknown as Date });
      const line = formatLogLine(event);
      // Should still produce a formatted timestamp
      expect(line).toMatch(/^\[\d{4}-\d{2}-\d{2} \d{2}:\d{2}\]/);
    });
  });

  describe('appendLog', () => {
    it('should create log.md with header when file does not exist', async () => {
      const event = makeEvent();
      await appendLog(flowDir, event);

      const content = await readFile(join(flowDir, 'log.md'), 'utf-8');
      expect(content).toContain('# Heartbeat Log');
      expect(content).toContain('Auto-generated by the heartbeat daemon');
      expect(content).toContain('my-task: Task completed successfully');
    });

    it('should append to existing log without duplicating header', async () => {
      const event1 = makeEvent({ message: 'First entry' });
      const event2 = makeEvent({ message: 'Second entry' });

      await appendLog(flowDir, event1);
      await appendLog(flowDir, event2);

      const content = await readFile(join(flowDir, 'log.md'), 'utf-8');
      // Header should appear exactly once
      const headerCount = (content.match(/# Heartbeat Log/g) || []).length;
      expect(headerCount).toBe(1);

      expect(content).toContain('First entry');
      expect(content).toContain('Second entry');
    });

    it('should produce lines in chronological order', async () => {
      await appendLog(flowDir, makeEvent({ message: 'alpha' }));
      await appendLog(flowDir, makeEvent({ message: 'beta' }));
      await appendLog(flowDir, makeEvent({ message: 'gamma' }));

      const content = await readFile(join(flowDir, 'log.md'), 'utf-8');
      const alphaIdx = content.indexOf('alpha');
      const betaIdx = content.indexOf('beta');
      const gammaIdx = content.indexOf('gamma');

      expect(alphaIdx).toBeLessThan(betaIdx);
      expect(betaIdx).toBeLessThan(gammaIdx);
    });

    it('should auto-create the directory if needed', async () => {
      const nestedDir = join(flowDir, 'nested', 'flow');
      const event = makeEvent();

      await appendLog(nestedDir, event);

      const content = await readFile(join(nestedDir, 'log.md'), 'utf-8');
      expect(content).toContain('# Heartbeat Log');
    });
  });
});
