/**
 * Log writer — appends formatted one-liner entries to flow/log.md.
 * Auto-creates the file with a header if it does not exist.
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import type { NotificationEvent } from '../types.js';

const LOG_FILENAME = 'log.md';

const LOG_HEADER = `# Heartbeat Log

> Auto-generated by the heartbeat daemon. Do not edit manually.

`;

const LEVEL_ICONS: Record<string, string> = {
  info: '\u2705',   // checkmark
  warn: '\u23F8\uFE0F', // pause
  error: '\u274C',  // cross
};

/**
 * Format a Date as `[YYYY-MM-DD HH:MM]`.
 */
function formatTimestamp(date: Date): string {
  const y = date.getFullYear();
  const mo = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  const h = String(date.getHours()).padStart(2, '0');
  const mi = String(date.getMinutes()).padStart(2, '0');
  return `[${y}-${mo}-${d} ${h}:${mi}]`;
}

/**
 * Build a single log line from a NotificationEvent.
 *
 * Format: `[2026-03-17 14:00] <icon> <task>: <message>`
 */
export function formatLogLine(event: NotificationEvent): string {
  const ts = formatTimestamp(
    event.timestamp instanceof Date ? event.timestamp : new Date(event.timestamp),
  );
  const icon = LEVEL_ICONS[event.level] ?? '\u2139\uFE0F';
  return `${ts} ${icon} ${event.task}: ${event.message}`;
}

/**
 * Append a formatted log entry to flow/log.md.
 * Creates the file with a header if it does not exist.
 */
export async function appendLog(
  flowDir: string,
  event: NotificationEvent,
): Promise<void> {
  const filePath = join(flowDir, LOG_FILENAME);
  const dir = dirname(filePath);

  await mkdir(dir, { recursive: true });

  let existing = '';
  try {
    existing = await readFile(filePath, 'utf-8');
  } catch {
    // File does not exist — will create with header
  }

  const line = formatLogLine(event);

  if (!existing) {
    await writeFile(filePath, `${LOG_HEADER}${line}\n`, 'utf-8');
  } else {
    await writeFile(filePath, `${existing.trimEnd()}\n${line}\n`, 'utf-8');
  }
}
